# Generated by Django 5.2.12 on 2026-03-18 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhello', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
