# Generated by Django 4.2.29 on 2026-03-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myhello", "0002_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=150)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("last_login", models.DateTimeField(auto_now_add=True)),
                ("picture", models.CharField(max_length=2048)),
            ],
        ),
    ]
