# Generated by Django 4.2.29 on 2026-03-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myhello", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Department", models.CharField(max_length=100)),
                ("CourseTitle", models.CharField(max_length=100)),
                ("Instructor", models.CharField(max_length=100)),
            ],
        ),
    ]
